# Generated by Django 5.1.1 on 2026-01-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarymemory',
            old_name='email',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='temporarymemory',
            name='sent',
        ),
    ]
