# Generated by Django 5.1.1 on 2026-01-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_email_temporarymemory_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymemory',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
