# Generated by Django 5.1.1 on 2026-01-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_temporarymemory_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymemory',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
