# Generated by Django 5.1.1 on 2026-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_temporarymemory_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymemory',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
