# Generated by Django 5.1.1 on 2026-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/darkyellowduck_7G9vUMD.jpg', null=True, upload_to='images/'),
        ),
    ]
