# Generated by Django 5.1.1 on 2026-01-17 16:42

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=mainapp.models.default_avatar, null=True, upload_to='images/'),
        ),
    ]
