# Generated by Django 5.1.1 on 2026-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alemchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
