# Generated by Django 5.1.1 on 2026-01-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alemchat', '0002_message_is_read'),
        ('mainapp', '0011_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='mainapp.travelinfo'),
        ),
    ]
