# Generated by Django 5.1.1 on 2026-01-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alemchat', '0003_chatroom_travel'),
        ('mainapp', '0011_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='mainapp.travelinfo'),
        ),
    ]
